### ISSUE TITLE
Issue with new code implementation

### ISSUE THREAD

**Issue by w1h2s3** [CFEL-CMI/cmistark#1]
There seems to be a problem I keep running into where code I have written such as a new molecule in moleculeparameters.py or a new conversion in convert.py does not seem to be recognized as actually being there. I have tried adding the relevant code blocks to both file locations and am hit with either a "NameError: name 'molecule name' is not defined" and a reference to the line in cmistark_calculate_energy where the function is being called, or "option --moleculename is not recognized"  when attempting to call a new molecule or a "'cmistark.convert' has no attribute 'conversion name'" despite the name being defined / conversion being implemented.

**Comment by jokuha** [comment]
Did you actually install the updates, e.g., with `python setup.py install` or instead used the `develop` version to begin with?

**Comment by w1h2s3** [comment]
I installed the updates using the python setup.py install command after I extracted the folder

Edit: Discovered my mistake. Running the setup command after adding my blocks of code makes it work wonderfully. Thank you for your time
